name: Generate Combined Snake & Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Generate combined animation
        uses: Platane/snk@v3
        with:
          github_user_name: GuillerSantos
          outputs: |
            dist/combined-animation.svg?color_snake=#00ff41&color_dots=#ffff00,#ff6b6b,#4ecdc4,#45b7d1,#96ceb4&animation_duration=8s&multi_character=true
            dist/combined-animation-dark.svg?palette=github-dark&color_snake=#00ff41&color_dots=#ffff00,#ff6b6b,#4ecdc4,#45b7d1,#96ceb4&animation_duration=8s&multi_character=true

      - name: Deploy combined animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
