name: Generate Both Animations (Working)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GuillerSantos
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Deploy snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate-pacman:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: generate-snake

    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output

      - name: Generate pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: GuillerSantos

      - name: Deploy pacman
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
