name: Generate Epic Combined Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate epic combined animation
        uses: Platane/snk@v3
        with:
          github_user_name: GuillerSantos
          outputs: |
            dist/epic-animation.svg?color_snake=#00ff41&color_dots=#ffdd44,#ff6b6b,#4ecdc4,#45b7d1,#96ceb4,#ffeaa7&animation_duration=10s&style=pacman-snake
            dist/epic-animation-dark.svg?palette=github-dark&color_snake=#00ff41&color_dots=#ffdd44,#ff6b6b,#4ecdc4&animation_duration=10s&style=pacman-snake

      - name: Deploy epic animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
