name: Generate Pacman Animation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  regenerate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Regenerate pacman animation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: GuillerSantos

      - name: Deploy pacman to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          force_orphan: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
