name: Generate Snake & Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate Snake Animation
      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GuillerSantos
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&color_snake=#00ff41&color_dots=#c0c0c0,#4c566a,#5e81ac,#88c0d0,#a3be8c

      # Generate Pacman Animation
      - name: Generate pacman animation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: GuillerSantos

      # Deploy both to output branch
      - name: Deploy animations to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
